-- Converted from MySQL dump stark_table_procedures.sql (tables section).
-- Identifiers keep their original MySQL names (quoted).

CREATE TABLE IF NOT EXISTS "chat_group" (
    "ChatGroupId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ChatGroupName" varchar(50) NOT NULL,
    "IsAllow" integer DEFAULT '1',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("ChatGroupId")
);

CREATE TABLE IF NOT EXISTS "chat_group_receiver" (
    "ChatGroupDetailId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ChatGroupId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("ChatGroupDetailId")
);

CREATE TABLE IF NOT EXISTS "chat_ledger_associate" (
    "ChatledgerassociateId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "AssociateLedgerId" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("ChatledgerassociateId")
);

CREATE TABLE IF NOT EXISTS "comman_master" (
    "CommanMasterId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanMasterName" varchar(200) NOT NULL,
    "CommanMasterType" integer NOT NULL,
    "LedgerId" bigint NOT NULL,
    "ParentAgentLedgerId" bigint DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("CommanMasterId")
);

CREATE TABLE IF NOT EXISTS "declare_result" (
    "DeclareId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "DeclareDate" date NOT NULL,
    "DeclareNumber" integer NOT NULL,
    "IsNeeded" varchar(3) NOT NULL DEFAULT 'No' CHECK ("IsNeeded" IN ('Yes', 'No')),
    "ReDeclareNos" integer DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("DeclareId")
);

CREATE TABLE IF NOT EXISTS "hissa" (
    "HissaId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "HissaLedgerId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "Hissa" double precision NOT NULL,
    "HissaLimit" double precision NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("HissaId")
);

CREATE TABLE IF NOT EXISTS "hp_hissa" (
    "HPHissaId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint DEFAULT NULL,
    "LedgerId" bigint DEFAULT NULL,
    "HPLedgerId" bigint DEFAULT NULL,
    "VoucherId" bigint DEFAULT NULL,
    "VoucherDate" date NOT NULL,
    "HPFromDate" date DEFAULT NULL,
    "HPToDate" date DEFAULT NULL,
    "BaseAmount" double precision DEFAULT NULL,
    "HPPercent" double precision DEFAULT NULL,
    "HPAmount" double precision DEFAULT NULL,
    "RecordStatus" char(1) DEFAULT NULL,
    "AddedBy" varchar(50) DEFAULT NULL,
    "AddedDate" timestamp DEFAULT NULL,
    "UpdatedBy" varchar(50) DEFAULT NULL,
    "UpdatedDate" timestamp DEFAULT NULL,
    PRIMARY KEY ("HPHissaId")
);

CREATE TABLE IF NOT EXISTS "hp_settelment" (
    "HPSettelmentId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint DEFAULT NULL,
    "LedgerId" bigint DEFAULT NULL,
    "SettelmentLedgerId" bigint DEFAULT NULL,
    "VoucherId" bigint DEFAULT NULL,
    "VoucherDate" date NOT NULL,
    "SettelmentFromDate" date DEFAULT NULL,
    "SettelmentToDate" date DEFAULT NULL,
    "SettelmentAmount" double precision DEFAULT NULL,
    "RecordStatus" char(1) DEFAULT NULL,
    "AddedBy" varchar(50) DEFAULT NULL,
    "AddedDate" timestamp DEFAULT NULL,
    "UpdatedBy" varchar(50) DEFAULT NULL,
    "UpdatedDate" timestamp DEFAULT NULL,
    PRIMARY KEY ("HPSettelmentId")
);

CREATE TABLE IF NOT EXISTS "kist" (
    "KistId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "KistDate" date NOT NULL,
    "Amount" double precision NOT NULL,
    "KistType" varchar(50) NOT NULL,
    "KistStatus" varchar(6) DEFAULT 'UNPAID' CHECK ("KistStatus" IN ('UNPAID', 'PAID')),
    "PaidVoucherId" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("KistId")
);

CREATE TABLE IF NOT EXISTS "ledger" (
    "LedgerId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL DEFAULT '0',
    "ParentLedgerId" bigint NOT NULL DEFAULT '0',
    "LedgerName" varchar(80) NOT NULL,
    "RealName" varchar(50) NOT NULL DEFAULT '',
    "GroupId" integer NOT NULL,
    "AgentLedgerId" bigint NOT NULL,
    "LimitType" varchar(3) NOT NULL CHECK ("LimitType" IN ('NO', 'YES')),
    "DaraRate" double precision DEFAULT '0',
    "DaraCommission" double precision DEFAULT '0',
    "AkharRate" double precision DEFAULT '0',
    "AkharCommission" double precision DEFAULT '0',
    "Vapsi" double precision NOT NULL,
    "TPVapsi" varchar(3) NOT NULL CHECK ("TPVapsi" IN ('NO', 'YES')),
    "TPCommission" varchar(3) NOT NULL CHECK ("TPCommission" IN ('No', 'YES')),
    "IsHissa" varchar(3) NOT NULL CHECK ("IsHissa" IN ('NO', 'YES')),
    "IsDibba" varchar(3) NOT NULL CHECK ("IsDibba" IN ('NO', 'YES')),
    "DibbaAmount" double precision NOT NULL,
    "RefLedgerId" bigint NOT NULL DEFAULT '0',
    "HPLedgerId" bigint NOT NULL DEFAULT '0',
    "Grantor" varchar(50) NOT NULL DEFAULT '',
    "DealingType" varchar(7) DEFAULT 'DAILY' CHECK ("DealingType" IN ('DAILY', 'MONTHLY', '25K', '50K', '1L', '2K')),
    "IsReport" varchar(1) NOT NULL CHECK ("IsReport" IN ('1', '0')),
    "TransactionMode" smallint NOT NULL,
    "AccountStatus" varchar(1) NOT NULL CHECK ("AccountStatus" IN ('1', '0')),
    "IsHide" varchar(1) NOT NULL DEFAULT '0' CHECK ("IsHide" IN ('0', '1')),
    "ChatGroupId" bigint DEFAULT '0',
    "TransactionCappingAmount" double precision DEFAULT '0',
    "IsApplyLedgerConfigOnTransaction" integer DEFAULT '0',
    "IsRisky" smallint DEFAULT '1',
    "TransactionLock" integer DEFAULT '0',
    "IsTransactionAllow" smallint DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LedgerId")
);

CREATE TABLE IF NOT EXISTS "ledger_asign" (
    "LedgerAsignId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "AsignDate" date NOT NULL,
    "StaffLoginId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LedgerAsignId")
);

CREATE TABLE IF NOT EXISTS "ledger_feedback" (
    "FeedbackId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanFeedbackId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "AsignAgentLedgerId" bigint DEFAULT '0',
    "CashPickDate" date DEFAULT NULL,
    "FeedbackDate" date NOT NULL,
    "Balance" double precision NOT NULL DEFAULT '0',
    "Remark" text NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("FeedbackId")
);

CREATE TABLE IF NOT EXISTS "ledger_group" (
    "GroupId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "GroupName" varchar(50) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("GroupId")
);

CREATE TABLE IF NOT EXISTS "ledger_limit" (
    "LedgerId" bigint NOT NULL,
    "LedgerBalance" double precision DEFAULT NULL,
    "LedgerLimit" double precision DEFAULT NULL,
    "TransConsum" double precision DEFAULT NULL,
    "TransConsumAfterDeclare" double precision DEFAULT '0',
    "FinalLimit" double precision DEFAULT NULL,
    "RecordStatus" char(1) DEFAULT NULL,
    "AddedBy" varchar(50) DEFAULT NULL,
    "AddedDate" timestamp DEFAULT NULL,
    "UpdatedBy" varchar(50) DEFAULT NULL,
    "UpdatedDate" timestamp DEFAULT NULL,
    PRIMARY KEY ("LedgerId")
);

CREATE TABLE IF NOT EXISTS "ledger_telegram" (
    "LedgerTelegramId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint DEFAULT '0',
    "FirstName" varchar(45) DEFAULT '',
    "Mobile" varchar(20) NOT NULL,
    "TelegramId" bigint NOT NULL DEFAULT '0',
    "AccessHash" varchar(250) DEFAULT '',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LedgerTelegramId")
);

CREATE TABLE IF NOT EXISTS "login" (
    "LoginId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "LoginName" varchar(80) NOT NULL,
    "AliasName" varchar(30) DEFAULT '',
    "UserName" varchar(30) NOT NULL,
    "Password" varchar(80) NOT NULL,
    "IsPasswordChangeNeeded" integer DEFAULT '0',
    "LoginType" smallint NOT NULL,
    "Mobile" varchar(20) NOT NULL,
    "Address" varchar(50) DEFAULT '',
    "StaffWorkMode" integer NOT NULL DEFAULT '0',
    "AccountStatus" varchar(1) NOT NULL CHECK ("AccountStatus" IN ('1', '0')),
    "AccessToken" text,
    "AccessTokenWeb" text,
    "DeviceId" varchar(500) DEFAULT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LoginId")
);

CREATE TABLE IF NOT EXISTS "mainjantrinumbers" (
    "Num" integer DEFAULT NULL,
    "profit" double precision DEFAULT NULL,
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "mainjantrinumbersprofit" (
    "amount1" double precision DEFAULT NULL,
    "amount2" double precision DEFAULT NULL,
    "amount3" double precision DEFAULT NULL,
    "amount4" double precision DEFAULT NULL,
    "amount5" double precision DEFAULT NULL,
    "amount6" double precision DEFAULT NULL,
    "amount7" double precision DEFAULT NULL,
    "amount8" double precision DEFAULT NULL,
    "amount9" double precision DEFAULT NULL,
    "amount10" double precision DEFAULT NULL,
    "amount11" double precision DEFAULT NULL,
    "amount12" double precision DEFAULT NULL,
    "amount13" double precision DEFAULT NULL,
    "amount14" double precision DEFAULT NULL,
    "amount15" double precision DEFAULT NULL,
    "amount16" double precision DEFAULT NULL,
    "amount17" double precision DEFAULT NULL,
    "amount18" double precision DEFAULT NULL,
    "amount19" double precision DEFAULT NULL,
    "amount20" double precision DEFAULT NULL,
    "amount21" double precision DEFAULT NULL,
    "amount22" double precision DEFAULT NULL,
    "amount23" double precision DEFAULT NULL,
    "amount24" double precision DEFAULT NULL,
    "amount25" double precision DEFAULT NULL,
    "amount26" double precision DEFAULT NULL,
    "amount27" double precision DEFAULT NULL,
    "amount28" double precision DEFAULT NULL,
    "amount29" double precision DEFAULT NULL,
    "amount30" double precision DEFAULT NULL,
    "amount31" double precision DEFAULT NULL,
    "amount32" double precision DEFAULT NULL,
    "amount33" double precision DEFAULT NULL,
    "amount34" double precision DEFAULT NULL,
    "amount35" double precision DEFAULT NULL,
    "amount36" double precision DEFAULT NULL,
    "amount37" double precision DEFAULT NULL,
    "amount38" double precision DEFAULT NULL,
    "amount39" double precision DEFAULT NULL,
    "amount40" double precision DEFAULT NULL,
    "amount41" double precision DEFAULT NULL,
    "amount42" double precision DEFAULT NULL,
    "amount43" double precision DEFAULT NULL,
    "amount44" double precision DEFAULT NULL,
    "amount45" double precision DEFAULT NULL,
    "amount46" double precision DEFAULT NULL,
    "amount47" double precision DEFAULT NULL,
    "amount48" double precision DEFAULT NULL,
    "amount49" double precision DEFAULT NULL,
    "amount50" double precision DEFAULT NULL,
    "amount51" double precision DEFAULT NULL,
    "amount52" double precision DEFAULT NULL,
    "amount53" double precision DEFAULT NULL,
    "amount54" double precision DEFAULT NULL,
    "amount55" double precision DEFAULT NULL,
    "amount56" double precision DEFAULT NULL,
    "amount57" double precision DEFAULT NULL,
    "amount58" double precision DEFAULT NULL,
    "amount59" double precision DEFAULT NULL,
    "amount60" double precision DEFAULT NULL,
    "amount61" double precision DEFAULT NULL,
    "amount62" double precision DEFAULT NULL,
    "amount63" double precision DEFAULT NULL,
    "amount64" double precision DEFAULT NULL,
    "amount65" double precision DEFAULT NULL,
    "amount66" double precision DEFAULT NULL,
    "amount67" double precision DEFAULT NULL,
    "amount68" double precision DEFAULT NULL,
    "amount69" double precision DEFAULT NULL,
    "amount70" double precision DEFAULT NULL,
    "amount71" double precision DEFAULT NULL,
    "amount72" double precision DEFAULT NULL,
    "amount73" double precision DEFAULT NULL,
    "amount74" double precision DEFAULT NULL,
    "amount75" double precision DEFAULT NULL,
    "amount76" double precision DEFAULT NULL,
    "amount77" double precision DEFAULT NULL,
    "amount78" double precision DEFAULT NULL,
    "amount79" double precision DEFAULT NULL,
    "amount80" double precision DEFAULT NULL,
    "amount81" double precision DEFAULT NULL,
    "amount82" double precision DEFAULT NULL,
    "amount83" double precision DEFAULT NULL,
    "amount84" double precision DEFAULT NULL,
    "amount85" double precision DEFAULT NULL,
    "amount86" double precision DEFAULT NULL,
    "amount87" double precision DEFAULT NULL,
    "amount88" double precision DEFAULT NULL,
    "amount89" double precision DEFAULT NULL,
    "amount90" double precision DEFAULT NULL,
    "amount91" double precision DEFAULT NULL,
    "amount92" double precision DEFAULT NULL,
    "amount93" double precision DEFAULT NULL,
    "amount94" double precision DEFAULT NULL,
    "amount95" double precision DEFAULT NULL,
    "amount96" double precision DEFAULT NULL,
    "amount97" double precision DEFAULT NULL,
    "amount98" double precision DEFAULT NULL,
    "amount99" double precision DEFAULT NULL,
    "amount100" double precision DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "organization" (
    "OrganizationId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationOwnerName" varchar(30) NOT NULL,
    "OrganizationName" varchar(30) NOT NULL,
    "OrganizationLogoColor" varchar(20) NOT NULL,
    "OrganizationTheme" varchar(20) NOT NULL,
    "OrganizationThemeDesign" integer DEFAULT '0',
    "OrganizationAppAccess" integer DEFAULT '0',
    "OrganizationMobile" varchar(10) NOT NULL,
    "OrganizationAddress" varchar(60) NOT NULL,
    "OrganizationOnDomain" integer NOT NULL DEFAULT '0',
    "OrganizationDomainURL" varchar(100) NOT NULL DEFAULT '',
    "OrganizationSms" varchar(1) NOT NULL CHECK ("OrganizationSms" IN ('1', '0')),
    "OrganizationSmsUrl" varchar(100) NOT NULL,
    "OrganizationSmsUsername" varchar(30) NOT NULL,
    "OrganizationSmsPassword" varchar(30) NOT NULL,
    "OrganizationSmsPort" varchar(10) NOT NULL,
    "OrganizationSmsSenderId" varchar(10) NOT NULL,
    "OrganizationSmsToken" text NOT NULL,
    "IsTransactionEnable" varchar(1) NOT NULL CHECK ("IsTransactionEnable" IN ('1', '0')),
    "IsEnableTazzaPatti" integer NOT NULL DEFAULT '0',
    "IsMainJantriRoundOf" integer DEFAULT '0',
    "IsCollectionJantriRoundOf" integer DEFAULT '0',
    "IsMultiplyUpMainJantri" integer DEFAULT '0',
    "IsMultiplyUpCollection" integer DEFAULT '0',
    "RoundOffOnMainJantri" integer DEFAULT '50',
    "RoundOffOnCollection" integer DEFAULT '50',
    "skey_Random_Old" integer NOT NULL DEFAULT '1',
    "skey_Crossing" integer NOT NULL DEFAULT '1',
    "skey_FromTo" integer NOT NULL DEFAULT '1',
    "skey_Random_New" integer NOT NULL DEFAULT '1',
    "skey_OddEven" integer NOT NULL DEFAULT '0',
    "skey_EkdiDukdi" integer NOT NULL DEFAULT '0',
    "skey_Joda" integer NOT NULL DEFAULT '0',
    "skey_JodiDaane" integer DEFAULT '0',
    "IsVoucherVerify" smallint DEFAULT '0',
    "IsDashboardStaffGainerLooser" smallint DEFAULT '0',
    "IsAutoSalaryCreate" smallint DEFAULT '0',
    "IsAutoSalaryPaid" smallint DEFAULT '0',
    "IsTransactionAlreadyExist" smallint DEFAULT '0',
    "HissaNotApplyMode" integer DEFAULT '0',
    "VapsiWorkingDays" integer DEFAULT '0',
    "IsAutoUserNameForStaff" integer DEFAULT '0',
    "UnPaidKistLastDateOfProcess" date DEFAULT '1970-01-01',
    "UnPaidKistPopupForDashboard" integer DEFAULT '0',
    "IsBackLimitPopup" smallint DEFAULT '0',
    "AbsentLedgerLockDays" integer DEFAULT '0',
    "TelegramAllow" smallint DEFAULT '0',
    "TelegramUrl" varchar(250) DEFAULT '',
    "TelegramSession" text,
    "OrganizationStartDate" date NOT NULL,
    "OrganizationEndDate" date NOT NULL,
    "IsOrganizationAllow" varchar(1) NOT NULL CHECK ("IsOrganizationAllow" IN ('1', '0')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("OrganizationId")
);

CREATE TABLE IF NOT EXISTS "payroll_attendance" (
    "AttendanceId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "AttendanceDate" date NOT NULL,
    "AttendanceMonth" integer DEFAULT '0',
    "AttendanceYear" integer DEFAULT '0',
    "TotalDays" integer DEFAULT '0',
    "WorkingDays" integer DEFAULT '0',
    "PaidLeave" integer DEFAULT '0',
    "Absent" integer DEFAULT '0',
    "Present" integer DEFAULT '0',
    "MonthEndLeaveApplicable" integer DEFAULT '0',
    "TotalEntryCount" integer DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("AttendanceId")
);

CREATE TABLE IF NOT EXISTS "payroll_comman_master" (
    "CommanMasterId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanName" varchar(100) NOT NULL,
    "CommanType" integer DEFAULT '0',
    "IsAllow" integer DEFAULT '1',
    "CommanOrder" integer DEFAULT '1',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("CommanMasterId")
);

CREATE TABLE IF NOT EXISTS "payroll_issue_return_stock" (
    "IssueReturnStockId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "StaffStockId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanMasterId" bigint NOT NULL,
    "IssueDate" date NOT NULL,
    "Amount" double precision DEFAULT '0',
    "Quantity" integer DEFAULT '0',
    "Brand" varchar(100) NOT NULL,
    "BillPartNo" varchar(100) NOT NULL,
    "IsReturn" integer DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("IssueReturnStockId")
);

CREATE TABLE IF NOT EXISTS "payroll_leave" (
    "LeaveId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "LeaveDate" date NOT NULL,
    "IsPaid" integer DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LeaveId")
);

CREATE TABLE IF NOT EXISTS "payroll_salary" (
    "SalaryId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "SalaryDate" date NOT NULL,
    "SalaryMonth" integer DEFAULT '0',
    "SalaryYear" integer DEFAULT '0',
    "TotalDays" integer DEFAULT '0',
    "WorkingDays" integer DEFAULT '0',
    "PaidLeave" integer DEFAULT '0',
    "Absent" integer DEFAULT '0',
    "Present" integer DEFAULT '0',
    "TotalEntryCount" integer DEFAULT '0',
    "BasicSalary" double precision DEFAULT '0',
    "Allowances" double precision DEFAULT '0',
    "Deductions" double precision DEFAULT '0',
    "NetSalary" double precision DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("SalaryId")
);

CREATE TABLE IF NOT EXISTS "payroll_salary_detail" (
    "SalaryDetailId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "SalaryId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanMasterId" bigint NOT NULL,
    "Amount" double precision DEFAULT '0',
    "KistId" bigint NOT NULL,
    "DetailRemark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("SalaryDetailId")
);

CREATE TABLE IF NOT EXISTS "payroll_staff_stock" (
    "StaffStockId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LedgerId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanMasterId" bigint NOT NULL,
    "Amount" double precision DEFAULT '0',
    "Quantity" integer DEFAULT '0',
    "Brand" varchar(100) NOT NULL,
    "BillPartNo" varchar(100) NOT NULL,
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("StaffStockId")
);

CREATE TABLE IF NOT EXISTS "payroll_staff_structure" (
    "StructureId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "LedgerId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommanMasterId" bigint NOT NULL,
    "Amount" double precision DEFAULT '0',
    "AmountType" double precision DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("StructureId")
);

CREATE TABLE IF NOT EXISTS "payroll_staff_structure_default" (
    "DefaultStructureId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "CommanMasterId" bigint NOT NULL,
    "Amount" double precision DEFAULT '0',
    "AmountType" double precision DEFAULT '0',
    "Remark" varchar(100) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("DefaultStructureId")
);

CREATE TABLE IF NOT EXISTS "role" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleId" integer NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleName" varchar(50) NOT NULL,
    "IsTransaction" varchar(1) NOT NULL CHECK ("IsTransaction" IN ('1', '0')),
    "IsAllow" varchar(1) NOT NULL CHECK ("IsAllow" IN ('1', '0')),
    "Hissa" double precision NOT NULL DEFAULT '0',
    "DaraRate" double precision NOT NULL DEFAULT '0',
    "DaraCommission" double precision NOT NULL DEFAULT '0',
    "AkharRate" double precision NOT NULL DEFAULT '0',
    "AkharCommission" double precision NOT NULL DEFAULT '0',
    "Vapsi" double precision NOT NULL DEFAULT '0',
    "IsDashboardReDeclare" smallint DEFAULT '0',
    "IsWebLogin" smallint DEFAULT '0',
    "IsAppLogin" smallint DEFAULT '0',
    "IsDeclareTransactionConfig" smallint DEFAULT '0',
    "Message" varchar(4000) DEFAULT '',
    "FlashMessage" varchar(4000) DEFAULT '',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "role_permission" (
    "RolePermissionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "MenuId" bigint NOT NULL DEFAULT '0',
    "Title" varchar(50) NOT NULL,
    "Page" varchar(50) NOT NULL,
    "IsPageAllow" varchar(1) NOT NULL CHECK ("IsPageAllow" IN ('0', '1')),
    "IsOption" varchar(1) NOT NULL CHECK ("IsOption" IN ('0', '1')),
    "Add" varchar(1) NOT NULL CHECK ("Add" IN ('0', '1')),
    "Edit" varchar(1) NOT NULL CHECK ("Edit" IN ('0', '1')),
    "Delete" varchar(1) NOT NULL CHECK ("Delete" IN ('0', '1')),
    "Export" varchar(1) NOT NULL CHECK ("Export" IN ('0', '1')),
    "ViewType" varchar(4) NOT NULL CHECK ("ViewType" IN ('ALL', 'SELF')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("RolePermissionId")
);

CREATE TABLE IF NOT EXISTS "role_permission_denied" (
    "RolePermissionDeniedId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RolePermissionId" bigint NOT NULL,
    "LoginId" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("RolePermissionDeniedId")
);

CREATE TABLE IF NOT EXISTS "role_permission_transaction" (
    "RolePermissionTransactionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LoginId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "ShiftDate" date NOT NULL,
    "ExpiryDateTime" timestamp NOT NULL,
    "DataViewMode" smallint NOT NULL,
    "Page" varchar(50) NOT NULL,
    "IsPageAllow" varchar(1) NOT NULL CHECK ("IsPageAllow" IN ('0', '1')),
    "Add" varchar(1) NOT NULL CHECK ("Add" IN ('0', '1')),
    "Edit" varchar(1) NOT NULL CHECK ("Edit" IN ('0', '1')),
    "Delete" varchar(1) NOT NULL CHECK ("Delete" IN ('0', '1')),
    "Export" varchar(1) NOT NULL CHECK ("Export" IN ('0', '1')),
    "ViewType" varchar(1) NOT NULL CHECK ("ViewType" IN ('0', '1')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("RolePermissionTransactionId")
);

CREATE TABLE IF NOT EXISTS "shift" (
    "ShiftId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftName" varchar(50) NOT NULL,
    "ShiftDate" date NOT NULL,
    "ShiftNextDay" varchar(3) NOT NULL CHECK ("ShiftNextDay" IN ('No', 'Yes')),
    "ShiftFor" varchar(4) NOT NULL CHECK ("ShiftFor" IN ('BOTH', 'WEB', 'APP')),
    "ShiftOrder" bigint NOT NULL DEFAULT '0',
    "DaraRate" double precision NOT NULL DEFAULT '0',
    "DaraCommission" double precision NOT NULL DEFAULT '0',
    "AkharRate" double precision NOT NULL DEFAULT '0',
    "AkharCommission" double precision NOT NULL DEFAULT '0',
    "Tax" double precision NOT NULL DEFAULT '0',
    "IsTransToCompany" integer DEFAULT '0',
    "CompanyApiUrl" varchar(200) DEFAULT '',
    "CompanyUserName" varchar(200) DEFAULT '',
    "CompanyPassword" varchar(200) DEFAULT '',
    "CompanyShiftId" bigint DEFAULT '0',
    "ApiTimeRebateForTransaction" varchar(30) DEFAULT '0',
    "MainJantriTime" varchar(30) DEFAULT '0',
    "IsActive" varchar(1) NOT NULL CHECK ("IsActive" IN ('1', '0')),
    "IsTransactionCapping" smallint DEFAULT '0',
    "RoundOffOnCollection" smallint DEFAULT '0',
    "IsLagaiTransactionExist" smallint DEFAULT '0',
    "IsCreateVapsi" smallint DEFAULT '1',
    "IsApplyShiftConfigOnTransaction" integer DEFAULT '0',
    "ResultWebShiftId" integer DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("ShiftId")
);

CREATE TABLE IF NOT EXISTS "shift_company_ledger" (
    "CompanyLedgerId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "Username" varchar(50) NOT NULL,
    "Password" varchar(200) NOT NULL,
    "DaraRate" double precision NOT NULL,
    "DaraCommission" double precision NOT NULL,
    "AkharRate" double precision NOT NULL,
    "AkharCommission" double precision NOT NULL,
    "Tax" double precision NOT NULL,
    "Remark" varchar(200) NOT NULL,
    "IsAllow" smallint DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("CompanyLedgerId")
);

CREATE TABLE IF NOT EXISTS "shift_timing" (
    "ShiftTimeId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "ShiftId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "EndTime" varchar(50) NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("ShiftTimeId")
);

CREATE TABLE IF NOT EXISTS "sys_access_block" (
    "AccessBlockId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LoginId" bigint NOT NULL,
    "IP" varchar(100) NOT NULL,
    "Attempt" integer NOT NULL,
    "Remark" text,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("AccessBlockId")
);

CREATE TABLE IF NOT EXISTS "sys_flash_message_logs" (
    "LogId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleId" integer NOT NULL,
    "LoginId" bigint NOT NULL,
    "Logs" varchar(4000) DEFAULT '',
    "IsExpire" integer NOT NULL DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LogId")
);

CREATE TABLE IF NOT EXISTS "sys_ip_logs" (
    "LogId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LoginId" bigint NOT NULL,
    "Type" varchar(100) NOT NULL,
    "SubType" varchar(100) NOT NULL,
    "FieldName" varchar(50) NOT NULL,
    "FieldValue" bigint NOT NULL,
    "DeviceType" integer NOT NULL,
    "Ip" varchar(100) NOT NULL,
    "LatLong" varchar(100) NOT NULL,
    "Location" varchar(200) DEFAULT NULL,
    "Info" text,
    "Logs" text,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LogId")
);

CREATE TABLE IF NOT EXISTS "sys_logs" (
    "LogId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "LoginId" bigint NOT NULL,
    "Logs" text NOT NULL,
    "TableName" varchar(50) NOT NULL,
    "FieldName" varchar(50) NOT NULL,
    "FieldValue" bigint NOT NULL,
    "OldJson" text,
    "NewJson" text,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("LogId")
);

CREATE TABLE IF NOT EXISTS "sys_menu" (
    "MenuId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Menu" varchar(50) NOT NULL,
    "Order" bigint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("MenuId")
);

CREATE TABLE IF NOT EXISTS "sys_options" (
    "OptionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "Slug" varchar(50) NOT NULL,
    "Value" text,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("OptionId")
);

CREATE TABLE IF NOT EXISTS "sys_role" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "RoleName" varchar(50) NOT NULL,
    "IsTransaction" varchar(1) NOT NULL CHECK ("IsTransaction" IN ('1', '0')),
    "IsAllow" varchar(1) NOT NULL CHECK ("IsAllow" IN ('1', '0')),
    "Hissa" double precision NOT NULL DEFAULT '0',
    "DaraRate" double precision NOT NULL DEFAULT '0',
    "DaraCommission" double precision NOT NULL DEFAULT '0',
    "AkharRate" double precision NOT NULL DEFAULT '0',
    "AkharCommission" double precision NOT NULL DEFAULT '0',
    "Vapsi" double precision NOT NULL DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("RoleId")
);

CREATE TABLE IF NOT EXISTS "sys_role_permission" (
    "RolePermissionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "MenuId" bigint NOT NULL DEFAULT '0',
    "Title" varchar(50) NOT NULL,
    "Page" varchar(50) NOT NULL,
    "IsPageAllow" varchar(1) NOT NULL CHECK ("IsPageAllow" IN ('0', '1')),
    "IsOption" varchar(1) NOT NULL CHECK ("IsOption" IN ('0', '1')),
    "Add" varchar(1) NOT NULL CHECK ("Add" IN ('0', '1')),
    "Edit" varchar(1) NOT NULL CHECK ("Edit" IN ('0', '1')),
    "Delete" varchar(1) NOT NULL CHECK ("Delete" IN ('0', '1')),
    "Export" varchar(1) NOT NULL CHECK ("Export" IN ('0', '1')),
    "ViewType" varchar(4) NOT NULL CHECK ("ViewType" IN ('ALL', 'SELF')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(50) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(50) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("RolePermissionId")
);

CREATE TABLE IF NOT EXISTS "TEMP" (
    "TransactionDetailId" bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "third_party_commission" (
    "CommissionId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "CommissionLedgerId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "CommissionDara" double precision NOT NULL,
    "CommissionAkhar" double precision NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("CommissionId")
);

CREATE TABLE IF NOT EXISTS "third_party_vapsi" (
    "VapsiId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VapsiLedgerId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "Vapsi" double precision NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VapsiId")
);

CREATE TABLE IF NOT EXISTS "toppers_losser" (
    "NumberCount" bigint DEFAULT NULL,
    "TotalAmount" double precision DEFAULT NULL,
    "AddedBy" varchar(50) DEFAULT NULL,
    "Mobile" varchar(50) DEFAULT NULL,
    "Address" varchar(200) DEFAULT NULL,
    "LoginStatus" integer DEFAULT NULL,
    "LoginName" varchar(100) DEFAULT NULL,
    "LoginType" integer DEFAULT NULL,
    "RoleId" integer DEFAULT NULL,
    "RoleName" varchar(50) DEFAULT NULL,
    "TopFlag" integer DEFAULT NULL,
    "NumberCountOrder" bigint DEFAULT NULL,
    "OrganizationId" bigint DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS "transaction" (
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "TransactionDate" date NOT NULL,
    "TransactionMode" smallint NOT NULL,
    "TransactionType" varchar(1) NOT NULL CHECK ("TransactionType" IN ('J', 'U')),
    "KFlag" varchar(5) NOT NULL CHECK ("KFlag" IN ('False', 'True')),
    "EntryType" varchar(4) NOT NULL CHECK ("EntryType" IN ('Main', 'Sub')),
    "ClientRemarks" varchar(50) NOT NULL,
    "IsHissa" varchar(5) NOT NULL CHECK ("IsHissa" IN ('True', 'False')),
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "DaraRate" double precision NOT NULL,
    "DaraCommission" double precision NOT NULL,
    "AkharRate" double precision NOT NULL,
    "AkharCommission" double precision NOT NULL,
    "Tax" double precision NOT NULL DEFAULT '0',
    "TotalAmount" double precision NOT NULL,
    "TotalCommission" double precision NOT NULL,
    "TotalTax" double precision NOT NULL DEFAULT '0',
    "FinalAmount" double precision NOT NULL,
    "TransactionStartTime" timestamp NOT NULL,
    "DeviceType" varchar(3) NOT NULL CHECK ("DeviceType" IN ('WEB', 'APP')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionId")
);

CREATE TABLE IF NOT EXISTS "transaction_audit" (
    "TransactionAuditId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "ShiftDate" date DEFAULT NULL,
    "LedgerId" bigint NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountUpdated" double precision NOT NULL,
    "MistakeStatus" smallint NOT NULL,
    "ModifyStatus" smallint NOT NULL,
    "LastStatus" smallint NOT NULL,
    "Remark" text NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionAuditId")
);

CREATE TABLE IF NOT EXISTS "transaction_declare" (
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "TransactionDate" date NOT NULL,
    "TransactionMode" smallint NOT NULL,
    "TransactionType" varchar(1) NOT NULL CHECK ("TransactionType" IN ('J', 'U')),
    "KFlag" varchar(5) NOT NULL CHECK ("KFlag" IN ('False', 'True')),
    "EntryType" varchar(4) NOT NULL CHECK ("EntryType" IN ('Main', 'Sub')),
    "ClientRemarks" varchar(50) NOT NULL,
    "IsHissa" varchar(5) NOT NULL CHECK ("IsHissa" IN ('True', 'False')),
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "DaraRate" double precision NOT NULL,
    "DaraCommission" double precision NOT NULL,
    "AkharRate" double precision NOT NULL,
    "AkharCommission" double precision NOT NULL,
    "Tax" double precision NOT NULL DEFAULT '0',
    "TotalAmount" double precision NOT NULL,
    "TotalCommission" double precision NOT NULL,
    "TotalTax" double precision NOT NULL DEFAULT '0',
    "FinalAmount" double precision NOT NULL,
    "TransactionStartTime" timestamp NOT NULL,
    "DeviceType" varchar(3) NOT NULL CHECK ("DeviceType" IN ('WEB', 'APP')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionId")
);

CREATE TABLE IF NOT EXISTS "transaction_detail" (
    "TransactionDetailId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "NumberType" integer NOT NULL,
    "Number" varchar(4) NOT NULL,
    "Amount" double precision NOT NULL,
    "Rate" double precision NOT NULL,
    "Commission" double precision NOT NULL,
    "Tax" double precision NOT NULL DEFAULT '0',
    "FinalAmount" double precision NOT NULL,
    "OrderNumber" integer NOT NULL,
    "UpdateLimitFlag" integer DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionDetailId")
);

CREATE TABLE IF NOT EXISTS "transaction_detail_declare" (
    "TransactionDetailId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "Number" varchar(4) NOT NULL,
    "NumberType" integer NOT NULL,
    "Amount" double precision NOT NULL,
    "Rate" double precision NOT NULL,
    "Commission" double precision NOT NULL,
    "Tax" double precision NOT NULL DEFAULT '0',
    "FinalAmount" double precision NOT NULL,
    "OrderNumber" integer NOT NULL,
    "UpdateLimitFlag" integer DEFAULT '0',
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionDetailId")
);

CREATE TABLE IF NOT EXISTS "transaction_narration" (
    "TransactionNarrationId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "Type" varchar(30) NOT NULL,
    "Number1" varchar(30) NOT NULL,
    "Number2" varchar(30) NOT NULL,
    "Number3" varchar(30) NOT NULL,
    "Amount" double precision NOT NULL,
    "Joda" varchar(3) NOT NULL CHECK ("Joda" IN ('Yes', 'No')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionNarrationId")
);

CREATE TABLE IF NOT EXISTS "transaction_narration_declare" (
    "TransactionNarrationId" bigint NOT NULL,
    "TransactionId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "Type" varchar(30) NOT NULL,
    "Number1" varchar(30) NOT NULL,
    "Number2" varchar(30) NOT NULL,
    "Number3" varchar(30) NOT NULL,
    "Amount" double precision NOT NULL,
    "Joda" varchar(3) NOT NULL CHECK ("Joda" IN ('Yes', 'No')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("TransactionNarrationId")
);

CREATE TABLE IF NOT EXISTS "vapsi" (
    "VapsiId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint DEFAULT NULL,
    "LedgerId" bigint DEFAULT NULL,
    "ParentsLedgerId" bigint DEFAULT NULL,
    "VoucherId" bigint DEFAULT NULL,
    "VoucherDate" date NOT NULL,
    "VapsiFromDate" date DEFAULT NULL,
    "VapsiToDate" date DEFAULT NULL,
    "BaseAmount" double precision DEFAULT NULL,
    "VapsiPercent" double precision DEFAULT NULL,
    "VapsiAmount" double precision DEFAULT NULL,
    "VapsiOn" integer DEFAULT NULL,
    "RecordStatus" char(1) DEFAULT NULL,
    "AddedBy" varchar(50) DEFAULT NULL,
    "AddedDate" timestamp DEFAULT NULL,
    "UpdatedBy" varchar(50) DEFAULT NULL,
    "UpdatedDate" timestamp DEFAULT NULL,
    PRIMARY KEY ("VapsiId")
);

CREATE TABLE IF NOT EXISTS "voucher" (
    "VoucherId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "VoucherDate" date NOT NULL,
    "VoucherType" smallint NOT NULL,
    "Amount" double precision NOT NULL,
    "Remark" text NOT NULL,
    "LagaiKhai" integer DEFAULT '1',
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherId")
);

CREATE TABLE IF NOT EXISTS "voucher_audit" (
    "VoucherAuditId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "LedgerId" bigint NOT NULL,
    "OppositeLedgerId" bigint NOT NULL,
    "VoucherDate" date NOT NULL,
    "VoucherType" smallint NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountType" varchar(2) NOT NULL CHECK ("AmountType" IN ('Dr', 'Cr')),
    "Remark" text NOT NULL,
    "AuditType" smallint NOT NULL,
    "AuditStatus" smallint NOT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherAuditId")
);

CREATE TABLE IF NOT EXISTS "voucher_detail" (
    "VoucherDetailId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint NOT NULL,
    "OppositeLedgerId" bigint NOT NULL,
    "FromLedgerId" bigint DEFAULT '0',
    "VoucherType" integer DEFAULT NULL,
    "VoucherDetailType" smallint NOT NULL,
    "VoucherDate" date NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountType" varchar(2) NOT NULL CHECK ("AmountType" IN ('Dr', 'Cr')),
    "OpenAmount" bigint DEFAULT '0',
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "Flag1" varchar(50) NOT NULL,
    "Remark" varchar(200) NOT NULL,
    "MondayFinalFlag" varchar(5) NOT NULL CHECK ("MondayFinalFlag" IN ('True', 'False')),
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "VerifyBy" varchar(30) DEFAULT NULL,
    "VerifyDate" timestamp DEFAULT NULL,
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherDetailId")
);

CREATE TABLE IF NOT EXISTS "voucher_detail_dump" (
    "VoucherDetailId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint NOT NULL,
    "OppositeLedgerId" bigint NOT NULL,
    "FromLedgerId" bigint DEFAULT '0',
    "VoucherType" integer DEFAULT NULL,
    "VoucherDetailType" smallint NOT NULL,
    "VoucherDate" date NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountType" varchar(2) NOT NULL CHECK ("AmountType" IN ('Dr', 'Cr')),
    "OpenAmount" bigint DEFAULT '0',
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "Flag1" varchar(50) NOT NULL,
    "Remark" varchar(200) NOT NULL,
    "MondayFinalFlag" varchar(5) NOT NULL CHECK ("MondayFinalFlag" IN ('True', 'False')),
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherDetailId")
);

CREATE TABLE IF NOT EXISTS "voucher_detail_first" (
    "VoucherDetailId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint NOT NULL,
    "OppositeLedgerId" bigint NOT NULL,
    "FromLedgerId" bigint DEFAULT '0',
    "VoucherType" integer DEFAULT NULL,
    "VoucherDetailType" smallint NOT NULL,
    "VoucherDate" date NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountType" varchar(2) NOT NULL CHECK ("AmountType" IN ('Dr', 'Cr')),
    "OpenAmount" bigint DEFAULT '0',
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "Flag1" varchar(50) NOT NULL,
    "Remark" varchar(200) NOT NULL,
    "MondayFinalFlag" varchar(5) NOT NULL CHECK ("MondayFinalFlag" IN ('True', 'False')),
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherDetailId")
);

CREATE TABLE IF NOT EXISTS "voucher_detail_tmp" (
    "VoucherDetailId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "VoucherId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL DEFAULT '0',
    "LedgerId" bigint NOT NULL,
    "OppositeLedgerId" bigint NOT NULL,
    "FromLedgerId" bigint DEFAULT '0',
    "VoucherType" integer DEFAULT NULL,
    "VoucherDetailType" smallint NOT NULL,
    "VoucherDate" date NOT NULL,
    "Amount" double precision NOT NULL,
    "AmountType" varchar(2) NOT NULL CHECK ("AmountType" IN ('Dr', 'Cr')),
    "OpenAmount" bigint DEFAULT '0',
    "SelfHissa" double precision NOT NULL DEFAULT '0',
    "OtherHissa" double precision NOT NULL DEFAULT '0',
    "Flag1" varchar(50) NOT NULL,
    "Remark" varchar(200) NOT NULL,
    "MondayFinalFlag" varchar(5) NOT NULL CHECK ("MondayFinalFlag" IN ('True', 'False')),
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherDetailId")
);

CREATE TABLE IF NOT EXISTS "voucher_dump" (
    "VoucherId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "VoucherDate" date NOT NULL,
    "VoucherType" smallint NOT NULL,
    "Amount" double precision NOT NULL,
    "Remark" text NOT NULL,
    "LagaiKhai" integer DEFAULT '1',
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherId")
);

CREATE TABLE IF NOT EXISTS "voucher_first" (
    "VoucherId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "VoucherDate" date NOT NULL,
    "VoucherType" smallint NOT NULL,
    "Amount" double precision NOT NULL,
    "Remark" text NOT NULL,
    "LagaiKhai" integer DEFAULT '1',
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherId")
);

CREATE TABLE IF NOT EXISTS "voucher_tmp" (
    "VoucherId" bigint NOT NULL,
    "OrganizationId" bigint NOT NULL,
    "ShiftId" bigint NOT NULL,
    "VoucherDate" date NOT NULL,
    "VoucherType" smallint NOT NULL,
    "Amount" double precision NOT NULL,
    "Remark" text NOT NULL,
    "LagaiKhai" integer DEFAULT '1',
    "VoucherMode" varchar(6) DEFAULT 'MANUAL' CHECK ("VoucherMode" IN ('MANUAL', 'AUTO')),
    "RecordStatus" char(1) NOT NULL,
    "AddedBy" varchar(30) NOT NULL,
    "AddedDate" timestamp NOT NULL,
    "UpdatedBy" varchar(30) NOT NULL,
    "UpdatedDate" timestamp NOT NULL,
    PRIMARY KEY ("VoucherId")
);

CREATE INDEX IF NOT EXISTS "chat_group_ChatGroupId_idx" ON "chat_group" ("ChatGroupId");
CREATE INDEX IF NOT EXISTS "chat_group_OrganizationId_idx" ON "chat_group" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "chat_group_receiver_ChatGroupId_idx" ON "chat_group_receiver" ("ChatGroupId");
CREATE INDEX IF NOT EXISTS "chat_group_receiver_LedgerId_idx" ON "chat_group_receiver" ("LedgerId");
CREATE INDEX IF NOT EXISTS "chat_group_receiver_OrganizationId_idx" ON "chat_group_receiver" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "chat_ledger_associate_LedgerId_idx" ON "chat_ledger_associate" ("LedgerId");
CREATE INDEX IF NOT EXISTS "chat_ledger_associate_OrganizationId_idx" ON "chat_ledger_associate" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "comman_master_CommanMasterId_idx" ON "comman_master" ("CommanMasterId");
CREATE INDEX IF NOT EXISTS "comman_master_LedgerId_idx" ON "comman_master" ("LedgerId");
CREATE INDEX IF NOT EXISTS "comman_master_CommanMasterType_idx" ON "comman_master" ("CommanMasterType");
CREATE INDEX IF NOT EXISTS "declare_result_OrganizationId_idx" ON "declare_result" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "declare_result_ShiftId_idx" ON "declare_result" ("ShiftId");
CREATE INDEX IF NOT EXISTS "declare_result_DeclareDate_idx" ON "declare_result" ("DeclareDate");
CREATE INDEX IF NOT EXISTS "hissa_HissaId_idx" ON "hissa" ("HissaId");
CREATE INDEX IF NOT EXISTS "hissa_OrganizationId_idx" ON "hissa" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "hissa_LedgerId_idx" ON "hissa" ("LedgerId");
CREATE INDEX IF NOT EXISTS "hissa_HissaLedgerId_idx" ON "hissa" ("HissaLedgerId");
CREATE INDEX IF NOT EXISTS "hp_hissa_LedgerId_idx" ON "hp_hissa" ("LedgerId");
CREATE INDEX IF NOT EXISTS "kist_KistId_idx" ON "kist" ("KistId");
CREATE INDEX IF NOT EXISTS "kist_OrganizationId_idx" ON "kist" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "kist_LedgerId_idx" ON "kist" ("LedgerId");
CREATE INDEX IF NOT EXISTS "kist_VoucherId_idx" ON "kist" ("VoucherId");
CREATE INDEX IF NOT EXISTS "kist_KistDate_idx" ON "kist" ("KistDate");
CREATE INDEX IF NOT EXISTS "ledger_LedgerId_idx" ON "ledger" ("LedgerId");
CREATE INDEX IF NOT EXISTS "ledger_OrganizationId_idx" ON "ledger" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "ledger_GroupId_idx" ON "ledger" ("GroupId");
CREATE INDEX IF NOT EXISTS "ledger_ParentLedgerId_idx" ON "ledger" ("ParentLedgerId");
CREATE INDEX IF NOT EXISTS "ledger_RecordStatus_idx" ON "ledger" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "ledger_asign_StaffLoginId_idx" ON "ledger_asign" ("StaffLoginId");
CREATE INDEX IF NOT EXISTS "ledger_asign_OrganizationId_idx" ON "ledger_asign" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "ledger_asign_AsignDate_idx" ON "ledger_asign" ("AsignDate");
CREATE INDEX IF NOT EXISTS "ledger_asign_LedgerId_idx" ON "ledger_asign" ("LedgerId");
CREATE INDEX IF NOT EXISTS "ledger_feedback_FeedbackId_idx" ON "ledger_feedback" ("FeedbackId");
CREATE INDEX IF NOT EXISTS "ledger_feedback_LedgerId_idx" ON "ledger_feedback" ("LedgerId");
CREATE INDEX IF NOT EXISTS "ledger_feedback_CommanFeedbackId_idx" ON "ledger_feedback" ("CommanFeedbackId");
CREATE INDEX IF NOT EXISTS "ledger_group_GroupId_idx" ON "ledger_group" ("GroupId");
CREATE INDEX IF NOT EXISTS "ledger_limit_ledger_limit_LedgerId_idx" ON "ledger_limit" ("LedgerId");
CREATE INDEX IF NOT EXISTS "ledger_telegram_LedgerTelegramId_idx" ON "ledger_telegram" ("LedgerTelegramId");
CREATE INDEX IF NOT EXISTS "ledger_telegram_OrganizationId_idx" ON "ledger_telegram" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "ledger_telegram_TelegramId_idx" ON "ledger_telegram" ("TelegramId");
CREATE INDEX IF NOT EXISTS "ledger_telegram_LedgerId_idx" ON "ledger_telegram" ("LedgerId");
CREATE INDEX IF NOT EXISTS "login_LoginId_idx" ON "login" ("LoginId");
CREATE INDEX IF NOT EXISTS "login_OrganizationId_idx" ON "login" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "login_LedgerId_idx" ON "login" ("LedgerId");
CREATE INDEX IF NOT EXISTS "login_LoginType_idx" ON "login" ("LoginType");
CREATE INDEX IF NOT EXISTS "organization_OrganizationId_idx" ON "organization" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_attendance_AttendanceId_idx" ON "payroll_attendance" ("AttendanceId");
CREATE INDEX IF NOT EXISTS "payroll_attendance_LedgerId_idx" ON "payroll_attendance" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_attendance_OrganizationId_idx" ON "payroll_attendance" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_comman_master_CommanMasterId_idx" ON "payroll_comman_master" ("CommanMasterId");
CREATE INDEX IF NOT EXISTS "payroll_comman_master_OrganizationId_idx" ON "payroll_comman_master" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_issue_return_stock_IssueReturnStockId_idx" ON "payroll_issue_return_stock" ("IssueReturnStockId");
CREATE INDEX IF NOT EXISTS "payroll_issue_return_stock_LedgerId_idx" ON "payroll_issue_return_stock" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_issue_return_stock_StaffStockId_idx" ON "payroll_issue_return_stock" ("StaffStockId");
CREATE INDEX IF NOT EXISTS "payroll_issue_return_stock_OrganizationId_idx" ON "payroll_issue_return_stock" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_leave_LeaveId_idx" ON "payroll_leave" ("LeaveId");
CREATE INDEX IF NOT EXISTS "payroll_leave_LedgerId_idx" ON "payroll_leave" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_leave_OrganizationId_idx" ON "payroll_leave" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_salary_SalaryId_idx" ON "payroll_salary" ("SalaryId");
CREATE INDEX IF NOT EXISTS "payroll_salary_LedgerId_idx" ON "payroll_salary" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_salary_OrganizationId_idx" ON "payroll_salary" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_salary_detail_SalaryDetailId_idx" ON "payroll_salary_detail" ("SalaryDetailId");
CREATE INDEX IF NOT EXISTS "payroll_salary_detail_SalaryId_idx" ON "payroll_salary_detail" ("SalaryId");
CREATE INDEX IF NOT EXISTS "payroll_salary_detail_KistId_idx" ON "payroll_salary_detail" ("KistId");
CREATE INDEX IF NOT EXISTS "payroll_salary_detail_OrganizationId_idx" ON "payroll_salary_detail" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_staff_stock_StaffStockId_idx" ON "payroll_staff_stock" ("StaffStockId");
CREATE INDEX IF NOT EXISTS "payroll_staff_stock_LedgerId_idx" ON "payroll_staff_stock" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_staff_stock_OrganizationId_idx" ON "payroll_staff_stock" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_StructureId_idx" ON "payroll_staff_structure" ("StructureId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_LedgerId_idx" ON "payroll_staff_structure" ("LedgerId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_OrganizationId_idx" ON "payroll_staff_structure" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_default_DefaultStructureId_idx" ON "payroll_staff_structure_default" ("DefaultStructureId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_default_OrganizationId_idx" ON "payroll_staff_structure_default" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "payroll_staff_structure_default_RoleId_idx" ON "payroll_staff_structure_default" ("RoleId");
CREATE INDEX IF NOT EXISTS "role_Id_idx" ON "role" ("Id");
CREATE INDEX IF NOT EXISTS "role_permission_RolePermissionId_idx" ON "role_permission" ("RolePermissionId");
CREATE INDEX IF NOT EXISTS "role_permission_RoleId_idx" ON "role_permission" ("RoleId");
CREATE INDEX IF NOT EXISTS "role_permission_denied_RolePermissionDeniedId_idx" ON "role_permission_denied" ("RolePermissionDeniedId");
CREATE INDEX IF NOT EXISTS "role_permission_denied_RolePermissionId_idx" ON "role_permission_denied" ("RolePermissionId");
CREATE INDEX IF NOT EXISTS "role_permission_denied_LoginId_idx" ON "role_permission_denied" ("LoginId");
CREATE INDEX IF NOT EXISTS "role_permission_transaction_RolePermissionTransactionId_idx" ON "role_permission_transaction" ("RolePermissionTransactionId");
CREATE INDEX IF NOT EXISTS "role_permission_transaction_ShiftId_idx" ON "role_permission_transaction" ("ShiftId");
CREATE INDEX IF NOT EXISTS "role_permission_transaction_LoginId_idx" ON "role_permission_transaction" ("LoginId");
CREATE INDEX IF NOT EXISTS "shift_ShiftId_idx" ON "shift" ("ShiftId");
CREATE INDEX IF NOT EXISTS "shift_OrganizationId_idx" ON "shift" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "shift_company_ledger_CompanyLedgerId_idx" ON "shift_company_ledger" ("CompanyLedgerId");
CREATE INDEX IF NOT EXISTS "shift_company_ledger_OrganizationId_idx" ON "shift_company_ledger" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "shift_company_ledger_ShiftId_idx" ON "shift_company_ledger" ("ShiftId");
CREATE INDEX IF NOT EXISTS "shift_timing_ShiftTimeId_idx" ON "shift_timing" ("ShiftTimeId");
CREATE INDEX IF NOT EXISTS "shift_timing_OrganizationId_idx" ON "shift_timing" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "sys_access_block_AccessBlockId_idx" ON "sys_access_block" ("AccessBlockId");
CREATE INDEX IF NOT EXISTS "sys_access_block_LoginId_idx" ON "sys_access_block" ("LoginId");
CREATE INDEX IF NOT EXISTS "sys_flash_message_logs_LogId_idx" ON "sys_flash_message_logs" ("LogId");
CREATE INDEX IF NOT EXISTS "sys_flash_message_logs_OrganizationId_idx" ON "sys_flash_message_logs" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "sys_flash_message_logs_RoleId_idx" ON "sys_flash_message_logs" ("RoleId");
CREATE INDEX IF NOT EXISTS "sys_flash_message_logs_LoginId_idx" ON "sys_flash_message_logs" ("LoginId");
CREATE INDEX IF NOT EXISTS "sys_ip_logs_LogId_idx" ON "sys_ip_logs" ("LogId");
CREATE INDEX IF NOT EXISTS "sys_logs_LogId_idx" ON "sys_logs" ("LogId");
CREATE INDEX IF NOT EXISTS "sys_menu_MenuId_idx" ON "sys_menu" ("MenuId");
CREATE INDEX IF NOT EXISTS "sys_options_OptionId_idx" ON "sys_options" ("OptionId");
CREATE INDEX IF NOT EXISTS "sys_options_OrganizationId_idx" ON "sys_options" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "sys_role_RoleId_idx" ON "sys_role" ("RoleId");
CREATE INDEX IF NOT EXISTS "sys_role_permission_RolePermissionId_idx" ON "sys_role_permission" ("RolePermissionId");
CREATE INDEX IF NOT EXISTS "sys_role_permission_RoleId_idx" ON "sys_role_permission" ("RoleId");
CREATE INDEX IF NOT EXISTS "third_party_commission_CommissionId_idx" ON "third_party_commission" ("CommissionId");
CREATE INDEX IF NOT EXISTS "third_party_commission_OrganizationId_idx" ON "third_party_commission" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "third_party_commission_LedgerId_idx" ON "third_party_commission" ("LedgerId");
CREATE INDEX IF NOT EXISTS "third_party_commission_CommissionLedgerId_idx" ON "third_party_commission" ("CommissionLedgerId");
CREATE INDEX IF NOT EXISTS "third_party_vapsi_VapsiId_idx" ON "third_party_vapsi" ("VapsiId");
CREATE INDEX IF NOT EXISTS "third_party_vapsi_OrganizationId_idx" ON "third_party_vapsi" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "third_party_vapsi_LedgerId_idx" ON "third_party_vapsi" ("LedgerId");
CREATE INDEX IF NOT EXISTS "third_party_vapsi_VapsiLedgerId_idx" ON "third_party_vapsi" ("VapsiLedgerId");
CREATE INDEX IF NOT EXISTS "transaction_TransactionDate_idx" ON "transaction" ("TransactionDate");
CREATE INDEX IF NOT EXISTS "transaction_OrganizationId_idx" ON "transaction" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "transaction_LedgerId_idx" ON "transaction" ("LedgerId");
CREATE INDEX IF NOT EXISTS "transaction_ShiftId_idx" ON "transaction" ("ShiftId");
CREATE INDEX IF NOT EXISTS "transaction_transaction_TransactionId_idx" ON "transaction" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_transaction_RecordStatus_idx" ON "transaction" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "transaction_audit_TransactionId_idx" ON "transaction_audit" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_audit_OrganizationId_idx" ON "transaction_audit" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "transaction_audit_LedgerId_idx" ON "transaction_audit" ("LedgerId");
CREATE INDEX IF NOT EXISTS "transaction_audit_ShiftDate_idx" ON "transaction_audit" ("ShiftDate");
CREATE INDEX IF NOT EXISTS "transaction_declare_TransactionDate_idx" ON "transaction_declare" ("TransactionDate");
CREATE INDEX IF NOT EXISTS "transaction_declare_OrganizationId_idx" ON "transaction_declare" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "transaction_declare_LedgerId_idx" ON "transaction_declare" ("LedgerId");
CREATE INDEX IF NOT EXISTS "transaction_declare_ShiftId_idx" ON "transaction_declare" ("ShiftId");
CREATE INDEX IF NOT EXISTS "transaction_declare_transaction_declare_TransactionId_idx" ON "transaction_declare" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_declare_transaction_declare_RecordStatus_idx" ON "transaction_declare" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "transaction_detail_TransactionId_idx" ON "transaction_detail" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_detail_Number_idx" ON "transaction_detail" ("Number");
CREATE INDEX IF NOT EXISTS "transaction_detail_transaction_detail_RecordStatus_idx" ON "transaction_detail" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "transaction_detail_declare_TransactionId_idx" ON "transaction_detail_declare" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_detail_declare_Number_idx" ON "transaction_detail_declare" ("Number");
CREATE INDEX IF NOT EXISTS "transaction_detail_declare_transaction_detail_declare_Recor_idx" ON "transaction_detail_declare" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "transaction_narration_TransactionId_idx" ON "transaction_narration" ("TransactionId");
CREATE INDEX IF NOT EXISTS "transaction_narration_declare_TransactionId_idx" ON "transaction_narration_declare" ("TransactionId");
CREATE INDEX IF NOT EXISTS "vapsi_LedgerId_idx" ON "vapsi" ("LedgerId");
CREATE INDEX IF NOT EXISTS "voucher_OrganizationId_idx" ON "voucher" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_ShiftId_idx" ON "voucher" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_VoucherDate_idx" ON "voucher" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_VoucherType_idx" ON "voucher" ("VoucherType");
CREATE INDEX IF NOT EXISTS "voucher_VoucherId_idx" ON "voucher" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_RecordStatus_idx" ON "voucher" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "voucher_audit_OrganizationId_idx" ON "voucher_audit" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_audit_VoucherId_idx" ON "voucher_audit" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_audit_VoucherDate_idx" ON "voucher_audit" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_audit_LedgerId_idx" ON "voucher_audit" ("LedgerId");
CREATE INDEX IF NOT EXISTS "voucher_audit_OppositeLedgerId_idx" ON "voucher_audit" ("OppositeLedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_VoucherId_idx" ON "voucher_detail" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_detail_OrganizationId_idx" ON "voucher_detail" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_detail_LedgerId_idx" ON "voucher_detail" ("LedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_OppositeLedgerId_idx" ON "voucher_detail" ("OppositeLedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_AmountType_idx" ON "voucher_detail" ("AmountType");
CREATE INDEX IF NOT EXISTS "voucher_detail_VoucherDetailType_idx" ON "voucher_detail" ("VoucherDetailType");
CREATE INDEX IF NOT EXISTS "voucher_detail_RecordStatus_idx" ON "voucher_detail" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "voucher_detail_ShiftId_idx" ON "voucher_detail" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_detail_VoucherDate_idx" ON "voucher_detail" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_VoucherId_idx" ON "voucher_detail_first" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_OrganizationId_idx" ON "voucher_detail_first" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_LedgerId_idx" ON "voucher_detail_first" ("LedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_VoucherDetailType_idx" ON "voucher_detail_first" ("VoucherDetailType");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_RecordStatus_idx" ON "voucher_detail_first" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_ShiftId_idx" ON "voucher_detail_first" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_detail_first_VoucherDate_idx" ON "voucher_detail_first" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_VoucherId_idx" ON "voucher_detail_tmp" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_OrganizationId_idx" ON "voucher_detail_tmp" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_LedgerId_idx" ON "voucher_detail_tmp" ("LedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_OppositeLedgerId_idx" ON "voucher_detail_tmp" ("OppositeLedgerId");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_AmountType_idx" ON "voucher_detail_tmp" ("AmountType");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_VoucherDetailType_idx" ON "voucher_detail_tmp" ("VoucherDetailType");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_RecordStatus_idx" ON "voucher_detail_tmp" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_ShiftId_idx" ON "voucher_detail_tmp" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_detail_tmp_VoucherDate_idx" ON "voucher_detail_tmp" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_first_OrganizationId_idx" ON "voucher_first" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_first_ShiftId_idx" ON "voucher_first" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_first_VoucherDate_idx" ON "voucher_first" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_first_VoucherType_idx" ON "voucher_first" ("VoucherType");
CREATE INDEX IF NOT EXISTS "voucher_first_VoucherId_idx" ON "voucher_first" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_first_RecordStatus_idx" ON "voucher_first" ("RecordStatus");
CREATE INDEX IF NOT EXISTS "voucher_tmp_OrganizationId_idx" ON "voucher_tmp" ("OrganizationId");
CREATE INDEX IF NOT EXISTS "voucher_tmp_ShiftId_idx" ON "voucher_tmp" ("ShiftId");
CREATE INDEX IF NOT EXISTS "voucher_tmp_VoucherDate_idx" ON "voucher_tmp" ("VoucherDate");
CREATE INDEX IF NOT EXISTS "voucher_tmp_VoucherType_idx" ON "voucher_tmp" ("VoucherType");
CREATE INDEX IF NOT EXISTS "voucher_tmp_VoucherId_idx" ON "voucher_tmp" ("VoucherId");
CREATE INDEX IF NOT EXISTS "voucher_tmp_RecordStatus_idx" ON "voucher_tmp" ("RecordStatus");
